name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      USE_SAVED_DATA: 'False'
      PRODUCTION: 'True'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Lint
        run: poetry run pylint src
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH
      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.IDV_PROJECT }}
        run: flyctl deploy
